name: barbers_app
description: App móvil para barbería
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  dio: ^5.0.0
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  flutter_local_notifications: ^12.0.4
  cupertino_icons: ^1.0.5
  go_router: ^14.8.1
  google_fonts: ^6.3.2
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/barber-logo.jpg
    - assets/images/services/
    - assets/images/products/
